server:
  port: 8081

spring:
  profiles:
    include:
      - "secret"
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

# 파일 업로드 설정
#  servlet:
#    multipart:
#      enabled: true         # 파일 업로드 가능 여부
#      location: C:\\upload  # 업로드된 파일의 임시 저장 경로
#      max-request: 30MB     # 한번에 최대 업로드 가능 용량
#      max-file-size: 10MB   # 파일 하나의 최대 크기

  thymeleaf:
    cache: false

logging.level:
  org.hibernate.SQL: debug